# Generated by Django 4.2.11 on 2025-04-24 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='has_completed_profile',
            field=models.BooleanField(default=False),
        ),
    ]
